<?php

namespace OuiEatFrench\AdmindBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
* RegisterRepository
* This class was generated by the Doctrine ORM. Add your own custom
* repository methods below.
*/
class RegisterRepository extends EntityRepository
{
    public function findByName($name)
    {
        return $this->getEntityManager()->createQuery('SELECT * FROM product WHERE name = '.$name)->getResult();
    }
}
