oui_eat_french_public_cart_show:
    pattern:  /
    defaults: { _controller: OuiEatFrenchPublicBundle:Cart:show }

oui_eat_french_public_cart_add:
    pattern:  /add/{farmerProductId}
    defaults: { _controller: OuiEatFrenchPublicBundle:Cart:addToCart }