oui_eat_french_public_panier_show:
    pattern:  /
    defaults: { _controller: OuiEatFrenchPublicBundle:Cart:show }

oui_eat_french_public_panier_command:
    pattern:  /commander
    defaults: { _controller: OuiEatFrenchPublicBundle:Cart:command }