oui_eat_french_public_cart_show:
    pattern:  /
    defaults: { _controller: OuiEatFrenchPublicBundle:Cart:show }

oui_eat_french_public_cart_add:
    pattern:  /ajouter/{farmerProductId}
    defaults: { _controller: OuiEatFrenchPublicBundle:Cart:addToCart }

oui_eat_french_public_cart_remove:
    pattern:  /supprimer/{farmerProductCartId}
    defaults: { _controller: OuiEatFrenchPublicBundle:Cart:removeFromCart }