oui_eat_french_public_cart_show:
    pattern:  /
    defaults: { _controller: OuiEatFrenchPublicBundle:Cart:show }

oui_eat_french_public_cart_add:
    pattern:  /ajouter/{farmerProductId}
    defaults: { _controller: OuiEatFrenchPublicBundle:Cart:addToCart }

oui_eat_french_public_cart_remove:
    pattern:  /supprimer/{farmerProductCartId}
    defaults: { _controller: OuiEatFrenchPublicBundle:Cart:removeFromCart }

oui_eat_french_public_cart_reset:
    pattern:  /vider
    defaults: { _controller: OuiEatFrenchPublicBundle:Cart:resetCart }

oui_eat_french_public_cart_valid:
    pattern:  /valider/{order}
    defaults: { _controller: OuiEatFrenchPublicBundle:Cart:validCart }

oui_eat_french_public_cart_modify:
    pattern:  /modifier/{farmerProductCartId}
    defaults: { _controller: OuiEatFrenchPublicBundle:Cart:modifyProductInCart }