oui_eat_french_public_product_farmer_index:
    pattern:  /agriculteur/{productId}
    defaults: { _controller: OuiEatFrenchPublicBundle:Product:farmerProductSelected }

oui_eat_french_public_product_index:
    pattern:  /
    defaults: { _controller: OuiEatFrenchPublicBundle:Product:index }

oui_eat_french_public_product_ajax_farmer:
    pattern:  /ajax-farmer
    defaults: { _controller: OuiEatFrenchFarmerBundle:FarmerProduct:ajaxFarmer }

oui_eat_french_public_product_ajax:
    pattern:  /ajax
    defaults: { _controller: OuiEatFrenchAdminBundle:Product:ajax }
