oui_eat_french_public_product_farmer_index:
    pattern:  /agriculteur/{productId}/{page}
    defaults: { _controller: OuiEatFrenchPublicBundle:Product:farmerProductSelected, page : 1 }

oui_eat_french_public_product_ajax_farmer:
    pattern:  /ajax-farmer
    defaults: { _controller: OuiEatFrenchFarmerBundle:FarmerProduct:ajaxFarmer }

oui_eat_french_public_product_ajax:
    pattern:  /ajax
    defaults: { _controller: OuiEatFrenchAdminBundle:Product:ajax }

oui_eat_french_public_product_index:
    pattern:  /{page}
    defaults: { _controller: OuiEatFrenchPublicBundle:Product:index, page: 1 }
