oui_eat_french_admin_application_index:
    pattern:  /
    defaults: { _controller: OuiEatFrenchAdminBundle:Application:index }

oui_eat_french_admin_application_status:
    pattern:  /status/{id}/{status_id}
    defaults: { _controller: OuiEatFrenchAdminBundle:Application:status }

oui_eat_french_admin_application_show:
    pattern:  /voir/{id}
    defaults: { _controller: OuiEatFrenchAdminBundle:Application:show }
