oui_eat_french_farmer:
    resource: "@OuiEatFrenchFarmerBundle/Controller/"
    type:     annotation
    prefix:   /monstand

oui_eat_french_mailing:
    resource: "@OuiEatFrenchMailingBundle/Resources/config/routing.yml"
    prefix:   /

oui_eat_french_admin:
    resource: "@OuiEatFrenchAdminBundle/Resources/config/routing.yml"
    prefix:   /admin
