oui_eat_french_market:
    resource: "@OuiEatFrenchMarketBundle/Resources/config/routing.yml"
    prefix:   /

oui_eat_french_mailing:
    resource: "@OuiEatFrenchMailingBundle/Resources/config/routing.yml"
    prefix:   /mailing

oui_eat_french_common:
    resource: "@OuiEatFrenchCommonBundle/Resources/config/routing.yml"
    prefix:   /common
