oui_eat_french_public:
    resource: "@OuiEatFrenchPublicBundle/Resources/config/routing.yml"
    prefix:   /

# oui_eat_french_command:
#     resource: "@OuiEatFrenchCommandBundle/Resources/config/routing.yml"
#     prefix:   /mon-stand/{id}

# oui_eat_french_farmer_connection:
#     path:     /monstand/connexion
#     defaults: { _controller: OuiEatFrenchFarmerBundle:Security:login }

# oui_eat_french_farmer_connection_check:
#     path:     /mon-stand/connexion_check

oui_eat_french_farmer:
    resource: "@OuiEatFrenchFarmerBundle/Resources/config/routing.yml"
    prefix:   /mon-stand

# To deal with farmer inscriptions
oui_eat_french_farmer_user_register:
    pattern:  /producteur/inscription
    defaults: { _controller: OuiEatFrenchFarmerBundle:UserFarmer:register }

oui_eat_french_farmer_user_login:
    pattern:  /producteur/connexion
    defaults: { _controller: OuiEatFrenchFarmerBundle:UserFarmer:login }

oui_eat_french_farmer_user_login_check:
    pattern:  /mon-stand/check

oui_eat_french_farmer_user_auto_logout:
    pattern:  /mon-stand/deconnexion

oui_eat_french_mailing:
    resource: "@OuiEatFrenchMailingBundle/Resources/config/routing.yml"
    prefix:   /presentation

oui_eat_french_admin:
    resource: "@OuiEatFrenchAdminBundle/Resources/config/routing.yml"
    prefix:   /admin

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile_edit:
    resource: "@OuiEatFrenchUserBundle/Resources/config/routing.yml"
    prefix: /profile/modifier/{id}

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile
