oui_eat_french_market:
    resource: "@OuiEatFrenchMarketBundle/Resources/config/routing.yml"
    prefix:   /market

oui_eat_french_landing:
    resource: "@OuiEatFrenchLandingBundle/Resources/config/routing.yml"
    prefix:   /
