security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512
        Symfony\Component\Security\Core\User\User: plaintext
        OuiEatFrench\FarmerBundle\Entity\UserFarmer:
            algorithm: sha512
            encode_as_base64: false
            iterations: 1

    role_hierarchy:
        ROLE_USER:              ROLE_USER
        ROLE_USER_FARMER:       ROLE_USER
        ROLE_ADMIN:             ROLE_USER
        ROLE_SUPER_ADMIN:       [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        user_farmer_area:
            entity: { class: OuiEatFrenchFarmerBundle:UserFarmer, property: username }
        main:
            id: fos_user.user_provider.username

    firewalls:
        user_farmer_area:
            pattern: ^/mon-stand
            anonymous: true
            provider: user_farmer_area
            form_login:
                login_path: oui_eat_french_farmer_user_login
                check_path: oui_eat_french_farmer_user_login_check
            logout:
               path: oui_eat_french_farmer_user_logout
               target: /producteur/connexion
               invalidate_session: false
        main:
            pattern: ^/
            anonymous: true
            provider: main
            form_login:
                login_path: fos_user_security_login
                check_path: fos_user_security_check
            logout:
                path:       fos_user_security_logout
                target:     /logout
            remember_me:
                key:        %secret%

    access_control:
        - { path: ^/mon-stand, roles: ROLE_USER_FARMER }
