security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512
        OuiEatFrench\FarmerBundle\UserFarmer: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        user_farmer_area:
            entity: { class: OuiEatFrenchFarmerBundle:UserFarmer, property: email }
        main:
            id: fos_user.user_provider.username

    firewalls:
        # user_farmer_area:
        #     pattern: ^/monstand
        #     anonymous:      false
        #     provider:       user_farmer_area
        #     form_login:
        #         login_path: oui_eat_french_farmer_connection
        #         check_path: oui_eat_french_farmer_connection_check
        #    logout:
        #        path:   /monstand/deconnexion
        #        target: /monstand
        main:
            pattern: ^/
            anonymous:      true
            provider:       main
            form_login:
                login_path: fos_user_security_login
                check_path: fos_user_security_check
            logout:
                path:       fos_user_security_logout
                target:     /logout
            remember_me:
                key:        %secret%

    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        #- { path: ^/monstand, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        #- { path: ^/monstand/, roles: ROLE_USER_FARMER, requires_channel: https }