parameters:
#    oui_eat_french_market.example.class: OuiEatFrench\MarketBundle\Example

services:
#    oui_eat_french_market.example:
#        class: %oui_eat_french_market.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
