oui_eat_french_command_commandstatus_index:
    pattern:  /
    defaults: { _controller: OuiEatFrenchCommandBundle:CommandStatus:index }

oui_eat_french_command_commandstatus_create:
    pattern:  /ajouter
    defaults: { _controller: OuiEatFrenchCommandBundle:CommandStatus:create }

oui_eat_french_command_commandstatus_edit:
    pattern:  /editer/{id}
    defaults: { _controller: OuiEatFrenchCommandBundle:CommandStatus:edit }

oui_eat_french_command_commandstatus_delete:
    pattern:  /supprimer/{id}
    defaults: { _controller: OuiEatFrenchCommandBundle:CommandStatus:delete }
