oui_eat_french_public_home:
    resource: "@OuiEatFrenchPublicBundle/Resources/config/routing/home.yml"
    prefix: /

oui_eat_french_public_faq:
    resource: "@OuiEatFrenchPublicBundle/Resources/config/routing/faq.yml"
    prefix: /faq

oui_eat_french_public_product:
    resource: "@OuiEatFrenchPublicBundle/Resources/config/routing/product.yml"
    prefix: /produit

oui_eat_french_public_cart:
    resource: "@OuiEatFrenchPublicBundle/Resources/config/routing/cart.yml"
    prefix: /panier

oui_eat_french_public_farmer:
    resource: "@OuiEatFrenchPublicBundle/Resources/config/routing/farmer.yml"
    prefix: /producteur

oui_eat_french_public_account:
    pattern:  /mon-compte
    defaults: { _controller: OuiEatFrenchPublicBundle:Account:index }
