oui_eat_french_farmer_availability_index:
    pattern:  /
    defaults: { _controller: OuiEatFrenchFarmerBundle:AvailabilityFarmer:index }

oui_eat_french_farmer_availability_edit:
    pattern:  /{id}/editer
    defaults: { _controller: OuiEatFrenchFarmerBundle:AvailabilityFarmer:edit }
