oui_eat_french_farmer_command_index:
    pattern:  /
    defaults: { _controller: OuiEatFrenchFarmerBundle:Command:index }

oui_eat_french_farmer_command_ready:
    pattern:  /{id}/prete
    defaults: { _controller: OuiEatFrenchFarmerBundle:Command:ready }

oui_eat_french_farmer_command_closed:
    pattern:  /{id}/terminee
    defaults: { _controller: OuiEatFrenchFarmerBundle:Command:closed }

# oui_eat_french_farmer_command_delete:
#     pattern:  /{id}/supprimer
#     defaults: { _controller: OuiEatFrenchFarmerBundle:Command:delete }
