oui_eat_french_farmer_product_index:
    pattern:  /
    defaults: { _controller: OuiEatFrenchFarmerBundle:FarmerProduct:index }

oui_eat_french_farmer_product_create:
    pattern:  /ajouter
    defaults: { _controller: OuiEatFrenchFarmerBundle:FarmerProduct:create }

oui_eat_french_farmer_product_edit:
    pattern:  /editer/{id}
    defaults: { _controller: OuiEatFrenchFarmerBundle:FarmerProduct:edit }

oui_eat_french_farmer_product_delete:
    pattern:  /supprimer/{id}
    defaults: { _controller: OuiEatFrenchFarmerBundle:FarmerProduct:delete }
