oui_eat_french_user_farmer_index:
    pattern:  /
    defaults: { _controller: OuiEatFrenchFarmerBundle:UserFarmer:index }

oui_eat_french_user_farmer_create:
    pattern:  /creer
    defaults: { _controller: OuiEatFrenchFarmerBundle:UserFarmer:create }

oui_eat_french_user_farmer_edit:
    pattern:  /editer/{id}
    defaults: { _controller: OuiEatFrenchFarmerBundle:UserFarmer:edit }

oui_eat_french_user_farmer_edit:
    pattern:  /voir/{id}
    defaults: { _controller: OuiEatFrenchFarmerBundle:UserFarmer:show }

oui_eat_french_user_farmer_delete:
    pattern:  /supprimer/{id}
    defaults: { _controller: OuiEatFrenchFarmerBundle:UserFarmer:delete }
