oui_eat_french_farmer_availability_index:
    resource: "@OuiEatFrenchFarmerBundle/Resources/config/routing/availability.yml"
    prefix: /disponibilite

oui_eat_french_farmer_product:
    resource: "@OuiEatFrenchFarmerBundle/Resources/config/routing/product.yml"
    prefix: /produit

oui_eat_french_farmer_user:
    resource: "@OuiEatFrenchFarmerBundle/Resources/config/routing/user.yml"
    prefix: /

oui_eat_french_farmer_command:
    resource: "@OuiEatFrenchFarmerBundle/Resources/config/routing/command.yml"
    prefix: /commande
