parameters:
    oui_eat_french.admin.form.type.product.class: OuiEatFrench\AdminBundle\Form\ProductType
    oui_eat_french.admin.form.type.category.class: OuiEatFrench\AdminBundle\Form\CategoryType

services:
    oui_eat_french.admin.form.type.product:
        class: OuiEatFrench\AdminBundle\Form\ProductType
        arguments: [ @service_container ]
        tags:
              - { name: form.type, alias: ouieatfrench_adminbundle_producttype }

    oui_eat_french.admin.form.type.category:
            class: OuiEatFrench\AdminBundle\Form\CategoryType
            arguments: [ @service_container ]
            tags:
                  - { name: form.type, alias: ouieatfrench_adminbundle_categorytype }
