parameters:
    oui_eat_french.admin.form.type.product.class: OuiEatFrench\AdminBundle\Form\ProductType
    oui_eat_french.admin.form.type.category.class: OuiEatFrench\AdminBundle\Form\CategoryType
    oui_eat_french.admin.form.type.filter.class: OuiEatFrench\AdminBundle\Form\FilterType
    oui_eat_french.admin.form.type.faq.class: OuiEatFrench\AdminBundle\Form\FaqType
    oui_eat_french.admin.form.type.edito.class: OuiEatFrench\AdminBundle\Form\EditoType
    oui_eat_french.admin.form.type.unittype.class: OuiEatFrench\AdminBundle\Form\UnitTypeType
    oui_eat_french.admin.form.type.agriculturetype.class: OuiEatFrench\AdminBundle\Form\AgricultureTypeType
    oui_eat_french.admin.form.type.commandstatus.class: OuiEatFrench\AdminBundle\Form\CommandStatusType
    oui_eat_french.admin.form.type.cartstatus.class: OuiEatFrench\AdminBundle\Form\CartStatusType

services:
    oui_eat_french.admin.form.type.product:
        class: OuiEatFrench\AdminBundle\Form\ProductType
        arguments: [ @service_container ]
        tags:
              - { name: form.type, alias: ouieatfrench_adminbundle_producttype }

    oui_eat_french.admin.form.type.category:
            class: OuiEatFrench\AdminBundle\Form\CategoryType
            arguments: [ @service_container ]
            tags:
                  - { name: form.type, alias: ouieatfrench_adminbundle_categorytype }

    oui_eat_french.admin.form.type.filter:
            class: OuiEatFrench\AdminBundle\Form\FilterType
            arguments: [ @service_container ]
            tags:
                  - { name: form.type, alias: ouieatfrench_adminbundle_filtertype }

    oui_eat_french.admin.form.type.faq:
            class: OuiEatFrench\AdminBundle\Form\FaqType
            arguments: [ @service_container ]
            tags:
                  - { name: form.type, alias: ouieatfrench_adminbundle_faqtype }

    oui_eat_french.admin.form.type.edito:
            class: OuiEatFrench\AdminBundle\Form\EditoType
            arguments: [ @service_container ]
            tags:
                  - { name: form.type, alias: ouieatfrench_adminbundle_editotype }

    oui_eat_french.admin.form.type.unittype:
            class: OuiEatFrench\AdminBundle\Form\UnitTypeType
            arguments: [ @service_container ]
            tags:
                  - { name: form.type, alias: ouieatfrench_adminbundle_unittypetype }

    oui_eat_french.admin.form.type.agriculturetype:
            class: OuiEatFrench\AdminBundle\Form\AgricultureTypeType
            arguments: [ @service_container ]
            tags:
                  - { name: form.type, alias: ouieatfrench_adminbundle_agriculturetypetype }

    oui_eat_french.admin.form.type.commandstatus:
            class: OuiEatFrench\AdminBundle\Form\CommandStatusType
            arguments: [ @service_container ]
            tags:
                  - { name: form.type, alias: ouieatfrench_adminbundle_commandstatustype }

    oui_eat_french.admin.form.type.cartstatus:
            class: OuiEatFrench\AdminBundle\Form\CartStatusType
            arguments: [ @service_container ]
            tags:
                  - { name: form.type, alias: ouieatfrench_adminbundle_cartstatustype }
