oui_eat_french_admin:
    pattern:  /
    defaults: { _controller: OuiEatFrenchAdminBundle:Admin:index }

oui_eat_french_admin_product:
    resource: "@OuiEatFrenchAdminBundle/Resources/config/routing/product.yml"
    prefix: /produit

oui_eat_french_admin_category:
    resource: "@OuiEatFrenchAdminBundle/Resources/config/routing/category.yml"
    prefix: /categorie

oui_eat_french_admin_filter:
    resource: "@OuiEatFrenchAdminBundle/Resources/config/routing/filter.yml"
    prefix: /filtre

oui_eat_french_admin_faq:
    resource: "@OuiEatFrenchAdminBundle/Resources/config/routing/faq.yml"
    prefix: /faq

oui_eat_french_admin_user:
    resource: "@OuiEatFrenchAdminBundle/Resources/config/routing/user.yml"
    prefix: /user

oui_eat_french_admin_edito:
    resource: "@OuiEatFrenchAdminBundle/Resources/config/routing/edito.yml"
    prefix: /edito

oui_eat_french_admin_application:
    resource: "@OuiEatFrenchAdminBundle/Resources/config/routing/application.yml"
    prefix: /candidature

oui_eat_french_admin_unittype:
    resource: "@OuiEatFrenchAdminBundle/Resources/config/routing/unittype.yml"
    prefix: /type-unite

oui_eat_french_admin_agriculturetype:
    resource: "@OuiEatFrenchAdminBundle/Resources/config/routing/agriculturetype.yml"
    prefix: /type-agriculture

oui_eat_french_admin_commandstatus:
    resource: "@OuiEatFrenchAdminBundle/Resources/config/routing/commandstatus.yml"
    prefix: /statut-commande

oui_eat_french_admin_cartstatus:
    resource: "@OuiEatFrenchAdminBundle/Resources/config/routing/cartstatus.yml"
    prefix: /statut-panier
