oui_eat_french_admin:
    pattern:  /
    defaults: { _controller: OuiEatFrenchAdminBundle:Admin:index }

oui_eat_french_admin_product:
    resource: "@OuiEatFrenchAdminBundle/Resources/config/routing/product.yml"
    prefix: /produits

oui_eat_french_admin_category:
    resource: "@OuiEatFrenchAdminBundle/Resources/config/routing/category.yml"
    prefix: /categories

oui_eat_french_admin_filter:
    resource: "@OuiEatFrenchAdminBundle/Resources/config/routing/filter.yml"
    prefix: /filtres

oui_eat_french_admin_faq:
    resource: "@OuiEatFrenchAdminBundle/Resources/config/routing/faq.yml"
    prefix: /faq

oui_eat_french_admin_edito:
    resource: "@OuiEatFrenchAdminBundle/Resources/config/routing/edito.yml"
    prefix: /edito
