<?php

namespace OuiEatFrench\FarmerBundle\Repository;

use Doctrine\ORM\EntityRepository;
use OuiEatFrench\FarmerBundle\Entity\AvailabilityFarmer;

/**
* RegisterRepository
* This class was generated by the Doctrine ORM. Add your own custom
* repository methods below.
*/
class AvailabilityFarmerRepository extends EntityRepository
{
	public function findOneByFarmerAndSlot($farmer, $slot)
	{
	    $em = $this->getEntityManager();

	    $queryText  = "SELECT a FROM OuiEatFrenchFarmerBundle:AvailabilityFarmer a ";
	    $queryText .= "WHERE :slot MEMBER OF a.availabilitySlots";
	    $queryText .= " AND a.farmer = :farmer";

	    $query = $em->createQuery($queryText);
	    $query->setParameter('slot', $slot);
	    $query->setParameter('farmer', $farmer);

	    return $query->getSingleResult();
	}
}
