<?php

namespace OuiEatFrench\FarmerBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CommandRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommandRepository extends EntityRepository
{
	public function getCommandsInProgress($farmer, $paidStatus, $readyStatus) 
	{
        $q = $this->createQueryBuilder('c')
            ->select ('c')
            ->where('c.status = :paidStatus OR c.status = :readyStatus')
            ->andWhere('c.farmer = :farmer')
            ->setParameter('paidStatus', $paidStatus)
            ->setParameter('readyStatus', $readyStatus)
            ->setParameter('farmer', $farmer)
            ->getQuery();

        return $q->getResult();
	}
}
