<?php

namespace OuiEatFrench\FarmerBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
* RegisterRepository
* This class was generated by the Doctrine ORM. Add your own custom
* repository methods below.
*/
class FarmerProductRepository extends EntityRepository
{
    public function findFarmerProductByFilters($productId)
    {
        $q = $this->createQueryBuilder('fp')
            ->select ('fp')
            ->join('fp.product','p')
            ->where('p.id = :productId')
            ->setParameter('productId', $productId)
            ->getQuery();

        return $q->getResult();
    }
}
