<?php

namespace OuiEatFrench\FarmerBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
* RegisterRepository
* This class was generated by the Doctrine ORM. Add your own custom
* repository methods below.
*/
class UserFarmerRepository extends EntityRepository
{
    public function findFarmerByProductAndParent($productId)
    {
        $q = $this->createQueryBuilder('f')
            ->select ('f')
            ->join('f.farmerProducts','fp')
            ->join('fp.product','p')
            ->where('p.id = :productId OR p.parentProduct = :productId')
            ->setParameter('productId', $productId)
            ->getQuery();

        return $q->getResult();
    }
}
