parameters:
    oui_eat_french.mailing.form.type.landing_customer.class: OuiEatFrench\MailingBundle\Form\LandingCustomerType
    oui_eat_french.mailing.form.type.landing_seller.class: OuiEatFrench\MailingBundle\Form\LandingSellerType
    oui_eat_french.mailing.form.type.landing_both.class: OuiEatFrench\MailingBundle\Form\LandingBothType

services:
    oui_eat_french.mailing.form.type.landing_customer:
        class: OuiEatFrench\MailingBundle\Form\LandingCustomerType
        arguments: [ @service_container ]
        tags:
              - { name: form.type, alias: ouieatfrench_mailingbundle_landingcustomertype }

    oui_eat_french.mailing.form.type.landing_seller:
        class: OuiEatFrench\MailingBundle\Form\LandingSellerType
        arguments: [ @service_container ]
        tags:
              - { name: form.type, alias: ouieatfrench_mailingbundle_landingsellertype }

    oui_eat_french.mailing.form.type.landing_both:
        class: OuiEatFrench\MailingBundle\Form\LandingBothType
        arguments: [ @service_container ]
        tags:
              - { name: form.type, alias: ouieatfrench_mailingbundle_landingbothtype }
