oui_eat_french_mailing_landing:
    resource: "@OuiEatFrenchMailingBundle/Resources/config/routing/landing.yml"
    prefix: /

oui_eat_french_mailing:
    resource: "@OuiEatFrenchMailingBundle/Resources/config/routing/mailing.yml"
    prefix: /mailing
