oui_eat_french_mailing_landing:
    resource: "@OuiEatFrenchMailingBundle/Resources/config/routing/landing.yml"
    prefix: /landing

oui_eat_french_mailing:
    resource: "@OuiEatFrenchMailingBundle/Resources/config/routing/mailing.yml"
    prefix: /
