<?php

namespace OuiEatFrench\MailingBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MailingListRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MailingListRepository extends EntityRepository
{
}
