<?php

namespace OuiEatFrench\MailingBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * OriginRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OriginRepository extends EntityRepository
{
}
